package:
  name: psgeom
  version: "1.1.2"

source:
  git_url: https://github.com/slaclab/psgeom
  git_tag: "v1.1.2"

build:
  number: 1
  script:
    - pip install --no-deps --disable-pip-version-check .

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - matplotlib
    - psana-conda  

about:
  home: https://github.com/slaclab/psgeom
